### ISSUE TITLE
Lock above toggle in "row-mode"

### ISSUE THREAD

**Issue by noxhirsch** [iantrich/restriction-card#1]
When using the restricion card as a row, it would be nice to have the lock above the toggle or button etc.. like in thomaslovens toggle-lock-entity-row: https://github.com/thomasloven/lovelace-toggle-lock-entity-row
Because that where the user usually looks and clicks.

So in the case of rows it should be `restriction-lock-margin-left`

Anyway: Thank you very much for this great and really useful card!

**Comment by iantrich** [comment]
It's not that simple as there are lots of different row types, not just toggle. Current placement was the best compromise I could come up with on short notice. I'll probably add an override in the card as theme level won't work as you could have cover rows you want aligned differently than slider rows for example.

**Comment by iantrich** [comment]
this has been added

**Comment by Mariusthvdb** [comment]
please let me ask how to accomplish this lock-above-toggle? Can't find any hints in the docs.
Pardon me if I overlook the obvious..

**Comment by noxhirsch** [comment]
@Mariusthvdb: Just add this to your theme: `restriction-lock-row-margin-left: 94%`
