### ISSUE TITLE
Restriction Card not loaded 

### ISSUE THREAD

**Issue by Nilmoty** [iantrich/restriction-card#100]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nilmoty** [comment]
Hi,

Release with the issue: 1.2.9

Browser and Operating System: Chrome connected on VMWare with :
Home Assistant 2023.8.3
Supervisor 2023.09.2
Operating System 10.4
Frontend 20230802.1 - latest

Description of problem: Issue after start HACS, Restriction Card not loaded  

Javascript errors shown in the web inspector (if applicable):  I don't know how can I catch it.

**Comment by ildar170975** [comment]
How do you tell “not loaded”?

**Comment by Nilmoty** [comment]
Hello, I solved the problem. I had made a mistake. 
Sorry
