### ISSUE TITLE
Card not rendered on mobile

### ISSUE THREAD

**Issue by vazquezjm** [iantrich/restriction-card#101]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.2.9

**Last working release (if known):**
N/A

**Browser and Operating System:**
Home Assistant mobile App 2023.9.2-full on Android 13

**Description of problem:**
The card is not rendered in the HA Android App (it is on the browser)

**Code**
```type: custom:restriction-card
restrictions:
  confirm: null
  pin:
    code: 1234
card:
  type: button
  entity: button.porton
  icon: mdi:gesture-tap-button
  icon_height: 100px
```

![image](https://github.com/iantrich/restriction-card/assets/5269397/f3c330ca-4a07-451c-b288-f53b0fd1b770)

**Comment by ildar170975** [comment]
1. You have not provided a FULL code. At least a `type: xxxxx` line is missing.
2. The card does work at least in Chrome+Win10, iOS Companion App (iOS 15.x). Check if it works with a desktop browser.
4. If the card does not work in Android Companion App only - then this should be addressed to this App))). Start with resetting a Frontend cache on your app.

**Comment by vazquezjm** [comment]
> You have not provided a FULL code. At least a type: xxxxx line is missing.

Here's the full code for the card:

```
type: custom:restriction-card
restrictions:
  confirm: null
  pin:
    code: 1234
card:
  type: button
  entity: button.porton
  icon: mdi:gesture-tap-button
  icon_height: 100px
``` 

> The card does work at least in Chrome+Win10, iOS Companion App (iOS 15.x). Check your setup if it works with a desktop browser.

This is how it looks like in Chrome v117.0.5938.92 + Win 11: 
![image](https://github.com/iantrich/restriction-card/assets/5269397/82df836a-58d4-4934-8783-47736f6b7412)


> If the card does not work in Android Companion App only - then this should be addressed to this App))). Start with resetting a Frontend cache on your app.

I will post back

**Comment by vazquezjm** [comment]
> If the card does not work in Android Companion App only - then this should be addressed to this App))). Start with resetting a Frontend cache on your app.

Had to re-download the Frontend integration from within the Companion App and that solved the issue. Thanks
