### ISSUE TITLE
Cant exit from the page where download the restriction card. Conected by iphone

### ISSUE THREAD

**Issue by gorkavedia** [iantrich/restriction-card#103]
**Checklist:**

- [x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ildar170975** [comment]
Consider providing DETAILS - a detailed description of what you tried to do, what you got etc.
The issue is empty and hence will be closed if no details are provided.

**Comment by ildar170975** [comment]
No feedback from OP, closing.
