### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by milandzuris** [iantrich/restriction-card#105]
**Checklist:**
- [ . ] I updated to the latest version available
- [ . ] I cleared the cache of my browser

**Browser and Operating System:**
W10 Chrome, Edge.

**Description of problem:**
https://imgur.com/a/M5h2uxs

**Comment by ildar170975** [comment]
1. Change the issue title to reflect the actual issue.
2. Add a clear test description of the issue.
3. No code provided. Provide a properly formatted code for the problem card only.
4. The posted link follows to a GIF which is rather unclear; also, it contains plenty of other UI elements. Suggest to create a separate view to demonstrate the issue clearly.

Just a warning: such issues - seemingly made in a haste - will be closed if not fixed correspondingly.

**Comment by ildar170975** [comment]
No feedback from OP, closing.

**Comment by milandzuris** [comment]
> 1. Change the issue title to reflect the actual issue.
> 2. Add a clear test description of the issue.
> 3. No code provided. Provide a properly formatted code for the problem card only.
> 4. The posted link follows to a GIF which is rather unclear; also, it contains plenty of other UI elements. Suggest to create a separate view to demonstrate the issue clearly.
> 
> Just a warning: such issues - seemingly made in a haste - will be closed if not fixed correspondingly.

OO sorry

if I write the password, it won't unlock

Cfg:
      - type: custom:restriction-card
        duration: 0
        locked_icon: ''
        unlocked_icon: ''
        restrictions:
          pin:
            code: 987612345
        card:
          type: tile
          entity: input_button.node_red_restart
          name: Reboot
          icon: mdi:restart
          color: orange

**Comment by ildar170975** [comment]
This means that the card is immediately locked:
```
duration: 0
```
Change this to any other positive value.

**Comment by ildar170975** [comment]
Close the issue if solved.

**Comment by milandzuris** [comment]
> This means that the card is immediately locked:
> 
> ```
> duration: 0
> ```
> 
> Change this to any other positive value.

it works thx
