### ISSUE TITLE
add animated lock

### ISSUE THREAD

**Issue by Mariusthvdb** [iantrich/restriction-card#11]
**Is your feature request related to a problem? Please describe.**

The UX doesn't clearly present the options the user has, and show the user when to act. Since the restriction card lock is near the left icon, and not the right toggle, it presents some surprise/confusion for first users..

**Describe the solution you'd like**
Would be really nice if upon clicking, the lock would 'slide' to the open position, remain so for the regulated time, and closeup back again

**Describe alternatives you've considered**
toggle-lock-entity-row custom card does this in an elegant way, fading out the lock to symbolize the toggle can be toggled

**Additional context**

![Feb-02-2020 17-29-58](https://user-images.githubusercontent.com/33354141/73611392-bed7e700-45e1-11ea-93cd-99aa6cc2e021.gif)

thanks for considering

**Comment by iantrich** [comment]
Implemented in https://github.com/iantrich/restriction-card/releases/tag/1.2.4
