### ISSUE TITLE
Lock in input_number (slide) doesn't show the value

### ISSUE THREAD

**Issue by sermayoral** [iantrich/restriction-card#12]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

1.1.7

**Last working release (if known):**

Unknown

**Browser and Operating System:**

Firefox 72.0.2 and Windows 10, both in 64 bits. It also happens in the Android App

**Description of problem:**

When I put a lock in an input_number, after unlock it, I cannot see the value of the slide. This is not only an esthetic issue because It's very difficult to select the correct value. 

This is a screenshot of an input_number with a lock:

![sshot-1](https://user-images.githubusercontent.com/30116095/74469240-8e733100-4e9c-11ea-9f78-f8f8e1303b3c.jpg).

This is a screenshot of an input_number without a lock:

![sshot-2](https://user-images.githubusercontent.com/30116095/74469328-bb274880-4e9c-11ea-833f-16e532c8174f.jpg)

**Javascript errors shown in the web inspector (if applicable):**

Nothing

**Additional information:**

**Comment by ildar170975** [comment]
HA 2024.1, 1.2.9
Cannot reproduce the described glitch:

![изображение](https://github.com/iantrich/restriction-card/assets/71872483/c0391595-4beb-4d7d-85a8-be6d1f83d67a)

Closed.
