### ISSUE TITLE
Does not work on older Android (e.g. 7) applications using internal web components (like Home Assistant app itself).

### ISSUE THREAD

**Issue by jkolczasty** [iantrich/restriction-card#20]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

- 1.1.9 (HACS installation)

**Last working release (if known):**

- not known

**Browser and Operating System:**

- Android 7 SDK components (I guess)

**Description of problem:**

Application shows "Custom element doesn't exist: restriction card". On the very same device, it works on latest version of Chrome installed. It only happens on embedded web component in Android applications. Can not verify other versions.

**Javascript errors shown in the web inspector (if applicable):**

- not applicable

**Additional information:**

**Comment by iantrich** [comment]
I have no plans to support older devices, especially when it works on Chrome in the device.

**Comment by jkolczasty** [comment]
Looks like it's not restriction-card problem, but plugins in general in older android web component. Can't debug it right now, but seems like plugins are not loaded at all.
