### ISSUE TITLE
More secure?

### ISSUE THREAD

**Issue by fufs** [iantrich/restriction-card#26]
**Is your feature request related to a problem? Please describe.**
Well, is there a more secure way of doing this? As of now, I can just go Inspect element and delete the overlay and gain access to it. I know that it's not meant for secure applications, but I think it could be a bit harder to break compared to what's available now.
**Describe the solution you'd like**
I'm not sure, maybe an option to add a picture behind, which would be switched for the real card after a correct password has been given?
**Describe alternatives you've considered**

**Additional context**

**Comment by iantrich** [comment]
I have no plans to rewrite this. Client side security is inherintly insecure.
