### ISSUE TITLE
PIN prompt window colors... use theme by default.

### ISSUE THREAD

**Issue by user514** [iantrich/restriction-card#27]
**Is your feature request related to a problem? Please describe.**
To keep the 'entering PIN code windows' (and the unlock alert) using theme colors.

**Describe the solution you'd like**
Without configuring anything, that the add-on takes your principal themes colors and use them at the PIN prompt window.

**Describe alternatives you've considered**
Be able to configure manually, but it will be very nice if it does it takes the two or three principal parameters of the theme to tint the prompt window.

  Testing your card right now. Very nice and useful. Lock OVER the switches (using 95% from left) and a bit less transparent (as Tom suggests) should be the default. Thanks Ian!.

**Comment by iantrich** [comment]
prompt is not part of lovelace, just a browser prompt. If https://github.com/iantrich/restriction-card/issues/2 is done, it will be included
