### ISSUE TITLE
Limit the number of PIN retries to 5 and then wait for X minutes

### ISSUE THREAD

**Issue by user514** [iantrich/restriction-card#28]
**Is your feature request related to a problem? Please describe.**
It seems to be no limit of retries when entering the PIN number. Having in mind that it is a 4 numbers combination, my kids play to find the unlock code from their tablets and set the thermostat temperature to -20ºC

**Describe the solution you'd like**
I know it is not a super advanced system of security. I know it is not intended for that and that's great. But it covers 99% of the need to block family members access to certain actions. It will be nice to limit the number of retries to around five, and the block the enter pin window for 1 minute or whatever.

  That will be enough to stop brute force attacks from the future hackers at home.

**Describe alternatives you've considered**
There could be other ways of solving it, like including an alphanumeric password, etc. But working only with numbers, a delay will be enough.

  Thanks for hearing!.

**Comment by iantrich** [comment]
Great idea. Implemented in https://github.com/iantrich/restriction-card/releases/tag/1.2.2
