### ISSUE TITLE
Unrestrict the more-info

### ISSUE THREAD

**Issue by xenz698** [iantrich/restriction-card#29]
**Is your feature request related to a problem? Please describe.**
I was using your toggle-lock-entity-row component before. the toggle switch was locked and I can still click on the entity-name to look at the more-info screen. since it's now deprecate, thus I try out this out.

With restriction-card, seems like the restriction was apply not only to the toggle switch, but the whole row. 

My use case - I have group entities (2nd floor, 1st floor) which contain each floors light switches. 
On the main screen, I can see "2nd floor" is ON or OFF with the toggle lock so I won't accidentally turn on/off the whole floor. and when I tap on the entity name, it show individual lights within this group where I can toggle them individually.   When needed (eg. at night) I can unlock the lock on the main screen and turn off the whole floor.

I was hoping restriction card can yield the same function since the, now deprecated, toggle lock entity row component serve the purpose really really well.

**Describe the solution you'd like**
Would it be possible to unrestrict the entity name ? or add an option to choose restrict "whole row" or just the "toggle switch" only ?

**Describe alternatives you've considered**
- fall back to toggle-lock-entity-row component, use it until it no longer compatible 
- I can create a switch template that return ON/OFF text and use browser_mod to change the more-info to the group entities I had before (2nd floor, 1st floor), so on the main menu, a quick glance I can still see which floor lights were turn on. and I can get the "more-info" to show the individual entity and also toggle.

**Additional context**
a reference to what I mean by entity_name and toggle_switch on the screen

![feature_request](https://user-images.githubusercontent.com/29969334/81723468-b93b3a00-9437-11ea-95c5-70b16ab3227e.jpg)

**Comment by iantrich** [comment]
no. That's not how this works. It's a more generic approach to apply to all types. Allowing more-info effectively makes useless as well IMO
