### ISSUE TITLE
seems like  row: boolean is not optional 

### ISSUE THREAD

**Issue by xenz698** [iantrich/restriction-card#30]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
restriction card v1.1.9

**Last working release (if known):**

**Browser and Operating System:**
Chrome 81.0.4044.138 
Firefox 76.0.1 (64bit)
Windows 7 SP1

**Description of problem:**
Seems like the option __Row__ is not optional but it's a required item. According to the instruction I put in only two __Required__ options: __type__ and __card__
```
        - type: "custom:restriction-card"
          card:
            entity: group.second_floor
```
and it gave me this error message 
![image](https://user-images.githubusercontent.com/29969334/81724403-2f8c6c00-9439-11ea-9a62-e08cd10836f4.png)

until I put in
```
          row: true
```
Then it show up okay
![image](https://user-images.githubusercontent.com/29969334/81724601-7ed29c80-9439-11ea-8f71-7b9643a0d1ff.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
It's optional. If you want a row you use it

**Comment by elitemike** [comment]
I see the same behavior. Without row: true it does not work

**Comment by iantrich** [comment]
Without a config to see, there's nothing anyone can do for you
