### ISSUE TITLE
Lock location does not line up the same from mobile and desktop view

### ISSUE THREAD

**Issue by iptvcld** [iantrich/restriction-card#35]
restriction-lock-row-margin-left: 94%
  restriction-lock-margin-left: 94%
  restriction-regular-lock-color: "#000000"

MOBILE
![l1](https://user-images.githubusercontent.com/34818686/83149178-d0c92280-a0c7-11ea-81b8-a0522050a33c.jpg)

DESKTOP
![l2](https://user-images.githubusercontent.com/34818686/83149223-daeb2100-a0c7-11ea-8bd5-692d854e03b9.PNG)

One is more to the right and the other is more to the left - perhaps there should be an option to just center it on top of the toggle.  I changed it to 95% as well and it still looks off.

**Comment by iantrich** [comment]
difference in number of pixels in either display, makes for a difference in offsets by a slight amount. not something I'll be "fixing"
