### ISSUE TITLE
Make card appear in lovelace card picker?

### ISSUE THREAD

**Issue by OmgImAlexis** [iantrich/restriction-card#53]
**Is your feature request related to a problem? Please describe.**
I'd like to see the this added to the Lovelace card picker.

**Describe the solution you'd like**
```js
// Configure the preview in the Lovelace card picker
window.customCards = window.customCards || [];
window.customCards.push({
  type: 'restriction-card',
  name: 'Restriction Card',
  preview: false,
  description: 'A card to provide restrictions on Lovelace cards defined within.'
});
```

**Additional context**
I would add this myself but I'm not sure where you'd want it added since you don't just have a single flat js file.

**Comment by iantrich** [comment]
If I had a UI editor I think that would be nice, but as it is you have to do everything in yaml and don't see an advantage to adding this

**Comment by OmgImAlexis** [comment]
> If I had a UI editor I think that would be nice, but as it is you have to do everything in yaml and don't see an advantage to adding this

For people wanting to add it it’s quicker than having to check the readme every time for the exact name. This has helped me use this card a lot more in my dashboard. Would you reconsider?

**Comment by firestrife23** [comment]
I don't see a problem with adding this feature because Card Picker UI does allow you to edit YAML directly.

**Comment by OmgImAlexis** [comment]
@iantrich would you please reconsider this?

**Comment by iantrich** [comment]
The only thing it would populate is
```
type: custom:restriction-card
```
You'd still have to read the documentation

**Comment by OmgImAlexis** [comment]
Yes. For new people adding this card there nothing to really show it’s added. This helps.
