### ISSUE TITLE
allow use of Template for Lock Codes

### ISSUE THREAD

**Issue by TKpizza** [iantrich/restriction-card#55]
**Is your feature request related to a problem? Please describe.**
Not a problem but having this feture would make life easier. I would like to use a template or reference a entity value for the lock passwords so that i can change all a passwords without having to dig through all of my code.

**Describe the solution you'd like**
Allow Templates to be used for the lock password, or allow us to define an entity that the lock will use the state as the password.

**Describe alternatives you've considered**
i have tried using templates in the code editor but it didnt work

**Additional context**

**Comment by iantrich** [comment]
Use my config-template-card as an outer wrapper to accomplish this
