### ISSUE TITLE
Fade away animation not working

### ISSUE THREAD

**Issue by jreed509** [iantrich/restriction-card#63]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.2.6
HA Version: 2021.10.4

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Chrome/Win10
HA iOS App/iOS

**Description of problem:**
The fade away animation does not occur when unlocking a card. The lock icon still changes color and eventually disappears as expected. 

![2021-10-12_18-53-40](https://user-images.githubusercontent.com/29850802/137040181-aa4589dd-151b-40f4-bd94-52eed7cb0e01.gif)

**Javascript errors shown in the web inspector (if applicable):**
None
```

```

**Additional information:**
I've also tested installing old versions of restriction-card from hacs (back to 1.2.2) but I see the same behavior in all cases. I think this suggests a breaking change in HA or an issue with my configuration (although I don't know what that could be). I first installed this card on HA 2021.10.3 so I can't speak to if this happened on previous versions or not. 

The gif above includes the theme variable `--restriction-lock-row-margin-left: calc(100% - 32px);` to move the icon position, but I see the same behavior with no custom theming applied.

**Comment by iantrich** [comment]
fixed in 1.2.7
