### ISSUE TITLE
Lock row margine left not working?

### ISSUE THREAD

**Issue by criticallimit** [iantrich/restriction-card#65]
I have cards like this:

  - card:
      entity: switch.doerrautomat
      icon: hass:power
      state_color: true
    restrictions:
      confirm:
        text: Sicher?
    type: custom:restriction-card
    row: true
    restriction-lock-row-margin-left: 100px
    duration: 10

But  restriction-lock-row-margin-left: 100px does nothing. 
Want to place the Lock behind the switch text, not in front.

can you help?

thanx

**Comment by iantrich** [comment]
should be fixed in 1.2.7
