### ISSUE TITLE
restriction card interferes with input_select in 2022.3/4

### ISSUE THREAD

**Issue by Mariusthvdb** [iantrich/restriction-card#70]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
1.2.7 (console says 1.2.6..)
**Last working release (if known):**

**Browser and Operating System:**

any Browser in Mac

**Description of problem:**

oddity with input_select: (the lock of a) restriction card which is below the dropdown seems to interfere, and the select option isnt available because of that, (and asks for the confirmation set in the restriction card). Meaning it doesnt select the option, but clicking actions the restriction card row

<img width="242" alt="Schermafbeelding 2022-03-01 om 11 01 50" src="https://user-images.githubusercontent.com/33354141/156154569-a233b4c3-67df-4898-949c-35b8d923a82f.png">

Moving the lock to the right doesnt help. the input_select still isnt available over these rows popping up the confirmation dialogue.

<img width="347" alt="Schermafbeelding 2022-03-01 om 11 05 46" src="https://user-images.githubusercontent.com/33354141/156154575-d2efbe29-fdd4-4143-a47d-9b4b6211196f.png">

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

please see #beta on discord: https://discord.com/channels/330944238910963714/427516175237382144/948161828406571018

according to Thomas this is the line in the code that is causing this:

https://github.com/iantrich/restriction-card/blob/master/src/restriction-card.ts#L292

thanks for having a look!

**Comment by iantrich** [comment]
put the mod-card example in the readme

**Comment by Mariusthvdb** [comment]
will try later sure, for reference here is what solved it on my config using a decluttering card for easy:
```
card:
  type: custom:mod-card
  card_mod:
    style: |
      ha-card {
        z-index: 7;
        }
  card:
    type: custom:restriction-card
    row: true
    card:
      entity: '[[entity]]'
      secondary_info: last-updated
    restrictions:
      confirm:
        text: 'Weet je het zeker?'
```
