### ISSUE TITLE
There is a specific area that allows me to control the button despite the restriction

### ISSUE THREAD

**Issue by Regradert** [iantrich/restriction-card#71]
There seems to be a problem with the card button locking. If I click just when the gray selection circle appears in a specific area, the button is unlocked.

Here I have made a gif where I show the problem:

https://i.imgur.com/kShCkJ7.gif

In my case it is very dangerous for this to happen because I am using the restriction-card to mount and unmount a hard drive.

Here previously they also mentioned the problem:

https://community.home-assistant.io/t/lovelace-restriction-card-client-side-security/142889/135

My browser is ** Google Chrome Versión 99.0.4844.51 (Build oficial) (64 bits)**. I control the server from a Windows 10 computer.

Home Assistant version is 2022.3.2 and Restriction cards repository version is 1.2.7

EDIT: It also happens in the Android HOME ASSISTANT application, if you insist on that area, just when the circle appears, you end up activating it.

I've done some more research and it seems that the problem lies right here in the css file:

ha-switch {
    padding: 20px 5px; //I have tried to increase the padding top/bottom and it seems that the problem is solved.
}

**Comment by ildar170975** [comment]
Seems to be same - https://github.com/iantrich/restriction-card/issues/66

**Comment by ildar170975** [comment]
HA 2024.1
1.2.9
The behaviour does not appear anymore.
Closed.
