### ISSUE TITLE
Auto tap after unlock?!

### ISSUE THREAD

**Issue by pickonedev** [iantrich/restriction-card#76]
**Is your feature request related to a problem? Please describe.**
After I enter the proper PIN code, I need to click again the card, to activate it... 

**Describe the solution you'd like**
When I click the card, if I enter the proper PIN code, the card (button/entity/etc) should auto receive a tap

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by arunc1** [comment]
This would be a great feature! :)

**Comment by andjona** [comment]
Auto fire would be a great feature.

**Comment by fir3drag0n** [comment]
Yes fire the event again if pin or confirmation was has been done successfully
