### ISSUE TITLE
theme variables

### ISSUE THREAD

**Issue by niighthawk** [iantrich/restriction-card#81]
Can you show how to use the theme variable please I want to change icon color in those 4 variables? 

I already have the Card mod working, but cant figure how to change the Lock color in your hac

-restriction-regular-lock-color
-restriction-success-lock-color
-restriction-blocked-lock-color
-restriction-invalid--color

**Comment by niighthawk** [comment]
like this ? 

`style: |
  restriction-regular-lock-color {
    primary-text-color: red;
    }`
or this
`style: |
  restriction-regular-lock-color {
    color: red;
    }`

**Comment by ildar170975** [comment]
Go to community card-mod thread - 1st post - link at the bottom - styles for restriction-card

**Comment by niighthawk** [comment]
@ildar170975  can you post the link please, cant find your place you talk about... :(

**Comment by niighthawk** [comment]
Okay I found your code, and cant manage to make it work in my code  heres my code how to male the REGULAR LOCK to be BLACK  ?

`type: custom:restriction-card
restrictions:
  pin:
    text: USER CODE
    code: 1234
  block:
    text: PLEASE SEE ADMIN
    exemptions:
      - user: 09a5eededd0242128b56cba33684afc8
      - user: d91e630cc49745da8e74b7512668d633
card:
  type: picture-elements
  image: /local/cyclovac/cyclo-OFF.png
  elements:
    - type: image
      entity: switch.aspirateur
      state_image:
        'off': /local/cyclovac/cyclo-OFF.png
        'on': /local/cyclovac/cyclo-ON.gif
        unavailable: /local/cyclovac/cyclo-INDIS.png
      style:
        top: 50%
        left: 50%
        width: 100%
        height: 100%
        image-rendering: smooth
      tap_action:
        action: toggle
      hold_action:
        action: more-info
`

**Comment by ildar170975** [comment]
Check the code you posted.

**Comment by niighthawk** [comment]
I dont see any change in my code I posted ?

**Comment by ildar170975** [comment]
I mean - see HOW you posted your code, it is absolutely not readable.

**Comment by niighthawk** [comment]
I used the CODE  bracket .. not my fault if it showing that bad ... that why I post an image to give you a better view of my code ...

**Comment by ildar170975** [comment]
@niighthawk 
1. Information about how to change CSS theme variables in card-mod [was provided](https://github.com/iantrich/restriction-card/issues/81#issuecomment-1426560807).
2. Posted code does not contain a suggested card-mod code.

Is this issue still valid? Have you sorted this out?

**Comment by ildar170975** [comment]
No feedback from OP, closing.
