### ISSUE TITLE
Overlay in 1.2.8 still has some issues

### ISSUE THREAD

**Issue by alexruffell** [iantrich/restriction-card#93]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.2.8

**Last working release (if known):**
Several versions back, no idea on version number
**Browser and Operating System:**

**Description of problem:**

In the previous version immediately before 1.2.8 the overlay showed correctly over the toggle however if I opened a camera and enlarged the window, the overlay was now shown over the camera feed while it should have been hidden by the overlayed camera feed window. After the 1.2.8 update, the overlay no longer shows on the camera feed however it now shows under the toggle rather than over the toggle. 

See image below:

<img width="383" alt="image" src="https://github.com/iantrich/restriction-card/assets/4006944/4db28d7f-c019-4ccc-8f14-2c0e6700e608">

The tiny bit of red on the bottom two toggles is the lock now hidden by the toggle.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ToniCifre** [comment]
I have the same error. 
As I have seen, the 'overlay' remains below the 'card'. I'm not sure if it generates other errors, but adding 'z-index: 1' to 'overlay' solves the error.

**Comment by ildar170975** [comment]
Not sure that using `z-index` is a proper way in a long-time perspective...
Probably the whole "overlay" element should be move in DOM tree on a higher z-level.

**Comment by arboeh** [comment]
Same for me. z-index seems to be a workaround.

**Comment by seanosteen** [comment]
Woo Hoo! Update v.1.2.9 and z-index adjustments removed, The overlay issue appears to be resolved on my instance. Thank you!

**Comment by alexruffell** [comment]
1.2.9 indeed fixed the issue. The lock no longer appears under the toggle "knob" and also doesn't get superimposed on a camera feed that overlays (when maximized) the card using the restriction. Thanks for the fix!
